CREATE TABLE IF NOT EXISTS ads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    category VARCHAR(100),
    type VARCHAR(100),
    surface VARCHAR(10),
    price INT,
    city VARCHAR(100),
    zipcode VARCHAR(20),
    region VARCHAR(100),
    url VARCHAR(255) NOT NULL,
    image_url VARCHAR(255),
    author VARCHAR(100),
    contact VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_url (url)
);

ALTER TABLE ads
ADD COLUMN suspicious TINYINT(1) NOT NULL DEFAULT 0
AFTER contact;

ALTER TABLE ads
ADD COLUMN score TINYINT UNSIGNED NOT NULL DEFAULT 0
AFTER suspicious;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS favorites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    ad_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, ad_id)
)

ALTER TABLE favorites
    ADD CONSTRAINT fk_fav_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE favorites
    ADD CONSTRAINT fk_fav_ad
    FOREIGN KEY (ad_id) REFERENCES ads(id) ON DELETE CASCADE;